---
title: "Tentative Class Schedule"
author: "Will Doyle"
date: "2026-01-09"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

January 8, 2026 Intro to Lasso

January 13, 2026 Cross Validation

January 15, 2026 Tuning Hyperparameters via Cross Validation

January 20, 2026 Elastic net for binary outcomes

January 22, 2026 Binary Outcomes, continued

January 27, 2026  The ice storm, part 1

January 29, 2026  The ice storm, part 2

February 3, 2026 Elastic net for multinomial outcomes

February 5, 2026 More cross-validation approaches: simulated annealing, Bayesian optimization; fun with feature engineering

February 10, 2026 Intro to SVM and kernels

February 12, 2026 SVM part 2: Tuning hyperparameters in SVM  and Deploying

February 17, 2026 Intro to tree-based models 

February 19, 2026 Random Forests

February 24, 2026 Random Forests

February 26, 2026 Xgboost, part 1

March 3, 2026 Xgboost, part 2 

March 4, 2025 Recap and case studies

March 10, 2026 Spring Break

March 12, 2026 Spring Break

March 17, 2026 Neural nets: architecture, pt. 1

March 19, 2026 Neural nets: architecture, pt. 2

March 24, 2026 Neural nets: backpropagation

March 26, 2026 Neural nets: hyperparameters

March 31, 2026 Neural nets: regularization and variable importance

April 2, 2026 Fitting Neural Nets: Image recognition application

April 7, 2026 

April 9, 2026 Fitting Neural Nets: Large k multinomial application

April 14, 2025 

April 16, 2025 Recap and Case studies
