---
title: "In-class: XGBoost Regression with Tidymodels (Kaggle-style train/test)"
output:githuub_document
---

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(vip)
library(finetune)
```

## Read in Data
```{r}
pf<-read_csv("student_performance.csv")%>%
  select(-id)%>%
  rename("ps"="productivity_score")

```


```{r}
pf_split <- initial_split(pf)
pf_train  <- training(pf_split)
pf_test   <- testing(pf_split)
```


## Recipe
```{r}
pf_formula <- as.formula("ps ~ .")

pf_rec <- recipe(pf_formula, pf_train) %>%
  update_role(student_id, new_role = "id") %>%
  update_role(ps, new_role = "outcome") %>%
  step_other(all_nominal_predictors(), threshold = 0.05) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_zv(all_predictors())%>%
  step_normalize(all_predictors())%>%
  step_interact(~starts_with("gender"):all_numeric_predictors())

```


```{r}

xgb_spec <- boost_tree(
  trees        = 100,
  tree_depth   = tune(),   # controls tree complexity
  min_n        = tune(),   # minimum observations per node
  loss_reduction = tune(), # γ: minimum gain to accept a split
  sample_size  = tune(),   # row subsampling fraction
  mtry         = tune(),   # column subsampling per split
  learn_rate   = tune()    # η: step size
) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

```


```{r}
pf_wf <- workflow() %>%
  add_recipe(pf_rec) %>%
  add_model(xgb_spec)
```


```{r}

xgb_grid <- grid_space_filling(
  tree_depth(),
  min_n(),
  loss_reduction(),
  sample_size = sample_prop(),
  finalize(mtry(), pf_train),
  learn_rate(),
  size = 30
)


```

```{r}
pf_rs<-mc_cv(pf_train,times=25)
```


```{r}
sim_anneal_control<-control_sim_anneal(cooling_coef=.02,
                                          verbose = TRUE,
                                          save_history = TRUE)
```


```{r}
fit_model <- TRUE

if (fit_model) {
  doParallel::registerDoParallel()
  xg_tune_res <- tune_sim_anneal(
    pf_wf,
    resamples=pf_rs,
    initial=4,
    control=sim_anneal_control
  )
  save(xg_tune_res, file = "xg_pf_tune_res.Rdata")
} else {
  load("xg_pf_tune_res.Rdata")
}

```

```{r}
show_best(xg_tune_res, metric = "rmse")
```

```{r}
best_rmse <- select_best(xg_tune_res, metric = "rmse")

final_xgb <- finalize_workflow(pf_wf, best_rmse)

final_res <- last_fit(final_xgb, pf_split)

collect_metrics(final_res)
```

